apiVersion: apps/v1
kind: Deployment
metadata:
  name: adguard-home
spec:
  selector:
    matchLabels:
      app: adguard-home
  template:
    metadata:
      labels:
        app: adguard-home
    spec:
      containers:
      - name: adguard-home
        image: adguard/adguardhome:latest
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 53
          protocol: TCP
        - containerPort: 53
          protocol: UDP
        - containerPort: 67
          protocol: UDP
        - containerPort: 68
          protocol: TCP
        - containerPort: 68
          protocol: UDP
        - containerPort: 80
          protocol: TCP
        - containerPort: 443
          protocol: TCP
        - containerPort: 443
          protocol: UDP
        - containerPort: 3000
          protocol: TCP
        - containerPort: 853
          protocol: TCP
        - containerPort: 784
          protocol: UDP
        - containerPort: 853
          protocol: UDP
        - containerPort: 8853
          protocol: UDP
        - containerPort: 5443
          protocol: TCP
        - containerPort: 5443
          protocol: UDP
        volumeMounts:
          - mountPath: /opt/adguardhome/work
            name: work
          - mountPath: /opt/adguardhome/conf
            name: config
      volumes:
        - name: work
          persistentVolumeClaim:
            claimName: adguard-home-work-pvc
        - name: config
          persistentVolumeClaim:
            claimName: adguard-home-config-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-home-config-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-home-work-pvc
spec:
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: adguard-home
  name: adguard-service-tcp
spec:
  type: LoadBalancer
  selector:
    app: adguard-home
  ports:
  - port: 53
    protocol: TCP
    name: dns
  - port: 68
    protocol: TCP
    name: dhcp1
  - port: 80
    protocol: TCP
    name: http
  - port: 443
    protocol: TCP
    name: https
  - port: 853
    protocol: TCP
    name: dns-tls
  - port: 3000
    protocol: TCP
    name: dns-https
  - port: 5443
    protocol: TCP
    name: dnscrypt
  loadBalancerIP: 172.16.40.41
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: adguard-home
  name: adguard-service-udp
spec:
  type: LoadBalancer
  selector:
    app: adguard-home
  ports:
  - port: 53
    protocol: UDP
    name: dns
  - port: 67
    protocol: UDP
    name: dhcp1
  - port: 68
    protocol: UDP
    name: dhcp2
  - port: 443
    protocol: UDP
    name: https
  - port: 784
    protocol: UDP
    name: dns-quic1
  - port: 853
    protocol: UDP
    name: dns-tls
  - port: 8853
    protocol: UDP
    name: dns-quic2
  - port: 5443
    protocol: UDP
    name: dnscrypt
  loadBalancerIP: 172.16.40.41